version: "3.8"

services:

  backend:
    build: ./backend
    command: flask run --port=80 --host=0.0.0.0


  backend2:
    build: ./backend
    command: flask run --port=80 --host=0.0.0.0


  backend3:
    build: ./backend
    command: flask run --port=80 --host=0.0.0.0


  nginx:
    build: ./nginx
    depends_on:
      - backend
      - backend2
      - backend3
    ports:
      - 9090:9090
